trigger: none

parameters:
  - name: awsRegion
    type: string
    default: eu-central-1
  - name: environment
    type: string
    default: nprod
  - name: awsCredentials
    type: string
    default: gpm_test
  - name: clusterName
    type: string
    default: App
  - name: applicationNamespace
    type: string
    default: optimachine-test
  - name: applicationName
    type: string
    default: qrcode-generator-test

resources:
  repositories:
    - repository: pipeline-templates
      ref: master
      type: git
      name: CAO-Gas-EmbddSrvcs/pipeline-templates


extends:
  template: docker/helm-uninstall-pipeline.yaml@pipeline-templates
  parameters:
    awsRegion: ${{ parameters.awsRegion }}
    environment: ${{ parameters.environment }}
    awsCredentials: ${{ parameters.awsCredentials }}
    clusterName:  ${{ parameters.clusterName }}
    applicationNamespace: ${{ parameters.applicationNamespace }}
    applicationName: ${{ parameters.applicationName }}
